{{- $fullName := include "kong-certificates.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: konnect-client-tls
  labels:
    {{- include "kong-certificates.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data: 
  tls.crt: {{ .Values.konnect_cluster_certificate | b64enc }}
  tls.key: {{ .Values.konnect_certificate_key | b64enc }}
