import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Trois sidebars distinctes, une par entrée de la navbar :
 * - ateliers : les guides pratiques (demos/)
 * - guides : introduction, comparatifs et conventions
 * - environnements : provisionnement des clusters (clusters/)
 *
 * Le contenu de website/docs/ est régénéré par scripts/sync-docs.mjs.
 */
const sidebars: SidebarsConfig = {
  ateliers: [{type: 'autogenerated', dirName: 'ateliers'}],
  guides: [
    {type: 'doc', id: 'index', label: 'Introduction'},
    {
      type: 'category',
      label: 'Comparatifs & recommandations',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'comparatifs'}],
    },
    {
      type: 'category',
      label: 'Conventions & contribution',
      collapsed: false,
      items: [{type: 'autogenerated', dirName: 'conventions'}],
    },
  ],
  environnements: [{type: 'autogenerated', dirName: 'environnements'}],
};

export default sidebars;
